name = "Anomaly_Explainer"
uuid = "bd5002b0-27d0-4761-a658-ccc901faf11c"
authors = ["your-name"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
